sudo: required

services:
- docker

language: bash

script:
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- curl -SLO https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz
- tar -xzf qemu-arm-static.tar.gz
- docker build -t nventiveux/docker-noip-duc:latest .
- docker images
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push nventiveux/docker-noip-duc:latest

branches:
  only:
    - master
